version: '3.7'

services:

  db:
    image: mongo:latest
    volumes:
      - db:/data/db

  giuseppe:
    image: ghcr.io/niceaesth/giuseppe:master
    container_name: giuseppe
    volumes:
      - ./config.json:/home/appuser/config.json
    depends_on:
      - db

volumes:
  db:
    driver: local
